#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use wenbinye\tars\cli\commands\AdapterCommand;
use wenbinye\tars\cli\commands\ConfigListCommand;
use wenbinye\tars\cli\commands\ConfigDeleteCommand;
use wenbinye\tars\cli\commands\ConfigSaveCommand;
use wenbinye\tars\cli\commands\ConfigureCommand;
use wenbinye\tars\cli\commands\NodeListCommand;
use wenbinye\tars\cli\commands\PatchListCommand;
use wenbinye\tars\cli\commands\PatchCommand;
use wenbinye\tars\cli\commands\ScaleDownCommand;
use wenbinye\tars\cli\commands\ScaleUpCommand;
use wenbinye\tars\cli\commands\ServerListCommand;
use wenbinye\tars\cli\commands\DeployCommand;
use wenbinye\tars\cli\commands\DestroyCommand;
use wenbinye\tars\cli\commands\StartCommand;
use wenbinye\tars\cli\commands\StopCommand;
use wenbinye\tars\cli\commands\TemplateListCommand;
use wenbinye\tars\cli\commands\TemplateSaveCommand;

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$application = new Application("tars", "@version@");
$application->add(new ConfigureCommand());
$application->add(new ServerListCommand());
$application->add(new DeployCommand());
$application->add(new StartCommand());
$application->add(new StopCommand());
$application->add(new DestroyCommand());
$application->add(new PatchListCommand());
$application->add(new PatchCommand());
$application->add(new AdapterCommand());
$application->add(new ConfigListCommand());
$application->add(new ConfigSaveCommand());
$application->add(new ConfigDeleteCommand());
$application->add(new TemplateListCommand());
$application->add(new TemplateSaveCommand());
$application->add(new NodeListCommand());
$application->add(new ScaleUpCommand());
$application->add(new ScaleDownCommand());
$application->run();
